name: mock_data
description: Generate random data using Dart. Can be used to create random strings,
  integers, names, colors, IPs, UUIDs, URLs and dates.
version: 2.0.0
homepage: https://github.com/PinkFrojd/mock_data

environment:
  sdk: '>=2.12.0 <3.0.0'

#dependencies:
#  path: ^1.4.1

dev_dependencies:
  test: ^1.17.5
  pedantic: ^1.11.0
