name: mock_data
description: Generate random data using Dart. Can be used to create random strings,
  integers, names, colors, IPs, url and dates.
version: 1.2.5
homepage: https://github.com/PinkFrojd/mock_data
author: Dinko Pehar <dinko.pehar.dev@gmail.com>

environment:
  sdk: '>=2.0.0 <3.0.0'

#dependencies:
#  path: ^1.4.1

dev_dependencies:
  test: ^1.0.0
