name: Mock Data CI

on:
  pull_request:
    branches:
    - master
  push:
    branches:
    - master

jobs:
  test:

    name: Run tests
    runs-on: ubuntu-latest

    container:
      image:  google/dart:latest

    steps:
    - uses: actions/checkout@v2
    - name: Telegram Message Notify - Trigger
      run: |
        curl --silent https://api.telegram.org/bot\${{ secrets.TELEGRAM_TOKEN }}/sendMessage\?chat_id\=${{ secrets.TELEGRAM_TO }}\&text\="Build Triggered by ${{ github.actor }} - ${{ github.event_name }}" > /dev/null
    - name: Install dependencies
      run: pub get
    - name: Run tests
      run: pub run test
    - name: Telegram Message Notify - FAILURE
      if: failure()
      run: |
        curl --silent https://api.telegram.org/bot\${{ secrets.TELEGRAM_TOKEN }}/sendMessage\?chat_id\=${{ secrets.TELEGRAM_TO }}\&text\="Build has *FAILED*."\&parse_mode\="Markdown" > /dev/null
        curl --silent https://api.telegram.org/bot\${{ secrets.TELEGRAM_TOKEN }}/sendSticker\?chat_id\=${{ secrets.TELEGRAM_TO }}\&sticker\=CAACAgIAAxkBAAMmXnD--5Hl7ayFoTNilFRaQf3Qh8MAAgMAA8A2TxOkKe7mffPAeBgE > /dev/null
    - name: Telegram Message Notify - SUCCESS
      if: success()
      run: |
        curl --silent https://api.telegram.org/bot\${{ secrets.TELEGRAM_TOKEN }}/sendMessage\?chat_id\=${{ secrets.TELEGRAM_TO }}\&text\="Build was *SUCCESS*."\&parse_mode\="Markdown" > /dev/null
        curl --silent https://api.telegram.org/bot\${{ secrets.TELEGRAM_TOKEN }}/sendSticker\?chat_id\=${{ secrets.TELEGRAM_TO }}\&sticker\=CAACAgIAAxkBAAMlXnD--Z2vyaFzqQcnyEVqnVs64cgAAggAA8A2TxNvbCYL3hqbaRgE > /dev/null

